# Generated by Django 5.2.8 on 2025-11-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faculty_university_studentgroup_faculty_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.university')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
