# Generated by Django 5.2.8 on 2025-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedpost_feedcomment_marketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN ₼'), ('USD', 'USD $'), ('EUR', 'EUR €'), ('RUB', 'RUB ₽')], default='AZN', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='category',
            field=models.CharField(choices=[('book', 'Kitab-Dərslik'), ('supply', 'Ləvazimatlar'), ('roommate', 'Otaq Yoldaşı'), ('electronics', 'Elektronika'), ('other', 'Digər')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='contact_info',
            field=models.CharField(max_length=100, verbose_name='Əlaqə (Tel/WP)'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='description',
            field=models.TextField(verbose_name='Ətraflı Məlumat'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Məhsulun Adı'),
        ),
    ]
