# Generated by Django 5.2.8 on 2025-11-22 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_marketitem_currency_alter_marketitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collective',
            options={'verbose_name': 'Çat Otağı', 'verbose_name_plural': '💬 Çat Otaqları'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Fakültə', 'verbose_name_plural': '📚 Fakültələr'},
        ),
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'verbose_name': 'Rəy', 'verbose_name_plural': '💬 Rəylər'},
        ),
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': '⚡ Axış Postları'},
        ),
        migrations.AlterModelOptions(
            name='marketitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Elan', 'verbose_name_plural': '🛒 Bazar Elanları'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mesaj', 'verbose_name_plural': '📨 Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xəbər', 'verbose_name_plural': '📰 Xəbərlər'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'İxtisas', 'verbose_name_plural': '🎓 İxtisaslar'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Tələbə Qrupu', 'verbose_name_plural': '👥 Tələbə Qrupları'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universitet', 'verbose_name_plural': '🏫 Universitetlər'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'İstifadəçi', 'verbose_name_plural': '👤 İstifadəçilər'},
        ),
        migrations.AlterModelOptions(
            name='userkyc',
            options={'verbose_name': 'Sənəd (KYC)', 'verbose_name_plural': '📂 Sənədlər (KYC)'},
        ),
        migrations.AlterField(
            model_name='collective',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaranma Tarixi'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collective', to='users.studentgroup', verbose_name='Aid Olduğu Qrup'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Otaq Adı'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Fakültə Adı'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='users.university', verbose_name='Universitet'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazan'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='content',
            field=models.TextField(verbose_name='Rəy'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonimdir?'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.feedpost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Müəllif'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='content',
            field=models.TextField(verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Tarixi'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonimdir?'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Bəyənmə Sayı'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='post_type',
            field=models.CharField(choices=[('confession', 'Etiraf'), ('debate', 'Debat'), ('question', 'Sual')], default='confession', max_length=20, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='category',
            field=models.CharField(choices=[('book', 'Kitab'), ('supply', 'Ləvazimat'), ('roommate', 'Otaq Yoldaşı'), ('electronics', 'Elektronika'), ('other', 'Digər')], max_length=20, verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='contact_info',
            field=models.CharField(max_length=100, verbose_name='Əlaqə'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='market_images/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to=settings.AUTH_USER_MODEL, verbose_name='Satıcı'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Elan Başlığı'),
        ),
        migrations.AlterField(
            model_name='message',
            name='collective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.collective', verbose_name='Kollektiv'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Mətn'), ('image', 'Şəkil'), ('audio', 'Səs'), ('video', 'Video')], default='text', max_length=10, verbose_name='Növ'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Göndərən'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaxt'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='news',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.university', verbose_name='Universitet (Boşsa Hamı Görür)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='users.faculty', verbose_name='Fakültə'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='İxtisas Adı'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.specialty', verbose_name='İxtisas'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uni_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Qısa Ad (Slug)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat Tarixi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personal?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Təsdiqlənib?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Tələbə'), ('teacher', 'Müəllim'), ('staff', 'İşçi'), ('admin', 'Admin')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='fin_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='FİN Kod'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='first_name',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentgroup', verbose_name='Qrup'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='id_card_back',
            field=models.ImageField(upload_to='kyc/back/', verbose_name='Vəsiqə (Arxa)'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='id_card_front',
            field=models.ImageField(upload_to='kyc/front/', verbose_name='Vəsiqə (Ön)'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='last_name',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='student_card',
            field=models.ImageField(upload_to='kyc/student/', verbose_name='Tələbə Bileti'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.university', verbose_name='Universitet'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi'),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Gözlənilir'), ('approved', 'Təsdiqləndi'), ('rejected', 'İmtina')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
